name = input("Type your name here: ")
print("Hello and Welcome "+ name +"!")
print()
first_number = int(input("Please Type the 1st number: "))
second_number = int(input("Please Type the 2nd number: "))
print()
print("Your answer is")
print(first_number*second_number)
print()
print("Thank you")
input("Press ENTER to exit")

